sudo: required
services:
 - docker

before_install:
 -  docker build -t azelante\react-test -f ./client/Dockerfile.dev ./client

scripts:
 - docker run -e CI=true azelante\react-test npm test -- --coverage


after_success:
 -  docker build -t azelante\multi-client ./client
 -  docker build -t azelante\multi-nginx ./nginx
 -  docker build -t azelante\multi-server ./server
 -  docker build -t azelante\multi-worker ./worker
 -  echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
 -  docker push azelante/multi-client
 -  docker push azelante/multi-nginx
 -  docker push azelante/multi-server
 -  docker push azelante/multi-worker